#!/bin/bash

haproxy_config_file="/etc/haproxy/haproxy.cfg"
destination_ip="10.10.144.2"

if [ ! -f "unique_ports.txt" ]; then
    echo "فایل unique_ports.txt پیدا نشد."
    exit 1
fi

echo "# HAProxy configuration generated by script" > "$haproxy_config_file"
echo "global" >> "$haproxy_config_file"
echo "    log /dev/log    local0" >> "$haproxy_config_file"
echo "    log /dev/log    local1 notice" >> "$haproxy_config_file"
echo "    chroot /var/lib/haproxy" >> "$haproxy_config_file"
echo "    stats socket /run/haproxy/admin.sock mode 660 level admin" >> "$haproxy_config_file"
echo "    stats timeout 30s" >> "$haproxy_config_file"
echo "    user haproxy" >> "$haproxy_config_file"
echo "    group haproxy" >> "$haproxy_config_file"
echo "    daemon" >> "$haproxy_config_file"
echo "" >> "$haproxy_config_file"
echo "defaults" >> "$haproxy_config_file"
echo "    log     global" >> "$haproxy_config_file"
echo "    mode    tcp" >> "$haproxy_config_file"
echo "    option  tcplog" >> "$haproxy_config_file"
echo "    option  dontlognull" >> "$haproxy_config_file"
echo "    timeout connect 5000ms" >> "$haproxy_config_file"
echo "    timeout client  50000ms" >> "$haproxy_config_file"
echo "    timeout server  50000ms" >> "$haproxy_config_file"
echo "" >> "$haproxy_config_file"

while IFS= read -r port
do
    port=$(echo "$port" | xargs)  

    if [[ "$port" =~ ^[0-9]+$ ]]; then
        echo "frontend frontend_$port" >> "$haproxy_config_file"
        echo "    bind *:$port" >> "$haproxy_config_file"
        echo "    default_backend backend_$port" >> "$haproxy_config_file"
        echo "" >> "$haproxy_config_file"
        echo "backend backend_$port" >> "$haproxy_config_file"
        echo "    server server_$port $destination_ip:$port" >> "$haproxy_config_file"
        echo "" >> "$haproxy_config_file"
    else
        echo "eroor '$port' eroor"
    fi
done < unique_ports.txt

echo "eroor."
systemctl restart haproxy

echo "suuccseees"
